In [0]:
import pandas as pd 
import numpy as np

In [0]:
#load the dataframe 
req = pd.read_csv('/Workspace/Users/dtruong4@stu.parkland.edu/global 2025/funding_requirements_global_clusters.csv')
req

     Unnamed: 0 countryCode    id  ...  requirements      funding percentFunded
0             1         AFG  1263  ...  3.412000e+07    7101118.0          21.0
1             3         AFG  1263  ...  9.327638e+07   80113551.0          86.0
2             4         AFG  1263  ...  1.791396e+08   28287010.0          16.0
3             5         AFG  1263  ...  1.089438e+09  202583088.0          19.0
4             6         AFG  1263  ...  2.797358e+08  127002611.0          45.0
..          ...         ...   ...  ...           ...          ...           ...
429         611         ZWE  1280  ...  6.833333e+06    1545466.0          23.0
430         612         ZWE  1280  ...  2.753330e+05     477106.0         173.0
431         614         ZWE  1280  ...  1.020833e+07    1224531.0          12.0
432         616         ZWE  1280  ...  8.525750e+05      37778.0           4.0
433         618         ZWE  1280  ...  1.160922e+07     287425.0           2.0

[434 rows x 13 columns]

In [0]:
# arr = np.array(req["countryCode"].unique())
# arr

# for i in arr: 
    # print("'", i, "'",":", ",")

' AFG ' : ,
' BFA ' : ,
' BGD ' : ,
' CAF ' : ,
' CMR ' : ,
' COD ' : ,
' COL ' : ,
' GTM ' : ,
' HND ' : ,
' HTI ' : ,
' LBN ' : ,
' MLI ' : ,
' MMR ' : ,
' MOZ ' : ,
' MWI ' : ,
' NER ' : ,
' NGA ' : ,
' PAK ' : ,
' PHL ' : ,
' PSE ' : ,
' SDN ' : ,
' SLV ' : ,
' SOM ' : ,
' SSD ' : ,
' SYR ' : ,
' TCD ' : ,
' UKR ' : ,
' VEN ' : ,
' VNM ' : ,
' YEM ' : ,
' ZMB ' : ,
' ZWE ' : ,

In [0]:
arr

array(['AFG', 'BFA', 'BGD', 'CAF', 'CMR', 'COD', 'COL', 'GTM', 'HND',
       'HTI', 'LBN', 'MLI', 'MMR', 'MOZ', 'MWI', 'NER', 'NGA', 'PAK',
       'PHL', 'PSE', 'SDN', 'SLV', 'SOM', 'SSD', 'SYR', 'TCD', 'UKR',
       'VEN', 'VNM', 'YEM', 'ZMB', 'ZWE'], dtype=object)

In [0]:
#country code: country name: 
countryNames = {
    'AFG': 'Afghanistan',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'CAF': 'Central African Republic', #not in the CBPF
    'CMR': 'Cameroon', #not in the CBPF
    'COD': 'Democratic Republic of the Congo', #not in the CBPF
    'COL': 'Colombia',
    'GTM': 'Guatemala', #not in the CBPF
    'HND': 'Honduras', #not in the CBPF
    'HTI': 'Haiti',
    'LBN': 'Lebanon',
    'MLI': 'Mali',
    'MMR': 'Myanmar', 
    'MOZ': 'Mozambique', 
    'MWI': 'Malawi', #not in the CBPF
    'NER': 'Niger', 
    'NGA': 'Nigeria', 
    'PAK': 'Pakistan', 
    'PHL': 'Philippines', #not in the CBPF
    'PSE': 'oPt', #needs to be reviewed
    'SDN': 'Sudan', 
    'SLV': 'El Salvador', #not in the CBPF
    'SOM': 'Somalia', 
    'SSD': 'South Sudan', 
    'SYR': 'Syria', 
    'TCD': 'Chad', #needs to be reviewed
    'UKR': 'Ukraine',
    'VEN': 'Venezuela',
    'VNM': 'Vietnam', #not in the CBPF
    'YEM': 'Yemen', 
    'ZMB': 'Zambia',#not in the CBPF 
    'ZWE': 'Zimbabwe', #not in the CBPF
}

In [0]:
#mapping & add col
req["countryName"] = req["countryCode"].map(countryNames)

req

     Unnamed: 0 countryCode    id  ...      funding percentFunded  countryName
0             1         AFG  1263  ...    7101118.0          21.0  Afghanistan
1             3         AFG  1263  ...   80113551.0          86.0  Afghanistan
2             4         AFG  1263  ...   28287010.0          16.0  Afghanistan
3             5         AFG  1263  ...  202583088.0          19.0  Afghanistan
4             6         AFG  1263  ...  127002611.0          45.0  Afghanistan
..          ...         ...   ...  ...          ...           ...          ...
429         611         ZWE  1280  ...    1545466.0          23.0     Zimbabwe
430         612         ZWE  1280  ...     477106.0         173.0     Zimbabwe
431         614         ZWE  1280  ...    1224531.0          12.0     Zimbabwe
432         616         ZWE  1280  ...      37778.0           4.0     Zimbabwe
433         618         ZWE  1280  ...     287425.0           2.0     Zimbabwe

[434 rows x 14 columns]

In [0]:
#changing col 
req.insert(2, "countryName", req.pop("countryName"))
req

     Unnamed: 0 countryCode  ...      funding  percentFunded
0             1         AFG  ...    7101118.0           21.0
1             3         AFG  ...   80113551.0           86.0
2             4         AFG  ...   28287010.0           16.0
3             5         AFG  ...  202583088.0           19.0
4             6         AFG  ...  127002611.0           45.0
..          ...         ...  ...          ...            ...
429         611         ZWE  ...    1545466.0           23.0
430         612         ZWE  ...     477106.0          173.0
431         614         ZWE  ...    1224531.0           12.0
432         616         ZWE  ...      37778.0            4.0
433         618         ZWE  ...     287425.0            2.0

[434 rows x 14 columns]

In [0]:
req.to_csv('funding_requirements_global_clusters_final.csv')
tada = "\N{PARTY POPPER}"
print(f"Done {tada}")

Done 🎉